
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FlatSharp FBS to C# compiler (source hash: 1.0.0.0BgpGKQDN3TxdxoC2GatqI7J5aVRhNTx3atprjZtxkw=)
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using FlatSharp;
using FlatSharp.Attributes;
namespace EGameFrame
{
    namespace Message
    {
        [FlatBufferEnum(typeof(System.SByte))]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public enum Color : System.SByte
        {
            Red = (sbyte)(0),
            Green = (sbyte)(1),
            Blue = (sbyte)(2),
        }

        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Equipment : FlatBufferUnion<global::EGameFrame.Message.Weapon>
        {
            public enum ItemKind : byte
            {
                Weapon = 1,
            }


            public ItemKind Kind => (ItemKind)base.Discriminator;

            public Equipment(global::EGameFrame.Message.Weapon value) : base(value)
            {
                checked
                { }
            }

            public global::EGameFrame.Message.Weapon Weapon => base.Item1;

            public new Equipment Clone(
                Func<global::EGameFrame.Message.Weapon, global::EGameFrame.Message.Weapon> cloneWeapon
            )
            {
                checked
                {
                    switch (base.Discriminator)
                    {
                        case 1:
                            return new Equipment(cloneWeapon(base.item1));
                    }

                    throw new System.InvalidOperationException();
                }
            }

            public new TReturn Switch<TState, TReturn>(
                TState state,
                Func<TState, TReturn> caseDefault
                , Func<TState, global::EGameFrame.Message.Weapon, TReturn> caseWeapon
            ) => base.Switch<TState, TReturn>(state, caseDefault, caseWeapon);
            public new TReturn Switch<TReturn>(
                Func<TReturn> caseDefault
                , Func<global::EGameFrame.Message.Weapon, TReturn> caseWeapon
            ) => base.Switch<TReturn>(caseDefault, caseWeapon);
            public new void Switch<TState>(
                TState state,
                Action<TState> caseDefault
                , Action<TState, global::EGameFrame.Message.Weapon> caseWeapon
            ) => base.Switch<TState>(state, caseDefault, caseWeapon);
            public new void Switch(
                Action caseDefault
                , Action<global::EGameFrame.Message.Weapon> caseWeapon
            ) => base.Switch(caseDefault, caseWeapon);
        }

        [FlatBufferStruct]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Vec3 : object
        {
            partial void OnInitialized();
            public Vec3()
            {
                checked
                { this.OnInitialized(); }
            }

            public Vec3(Vec3 source)
            {
                checked
                {
                    this.x = source.x;
                    this.y = source.y;
                    this.z = source.z;
                    this.OnInitialized();
                }
            }

            [FlatBufferItem(0)]
            public virtual System.Single x { get; set; }
            [FlatBufferItem(1)]
            public virtual System.Single y { get; set; }
            [FlatBufferItem(2)]
            public virtual System.Single z { get; set; }
        }
        [FlatBufferTable]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Monster : object
        {
            partial void OnInitialized();
            public Monster()
            {
                checked
                { this.OnInitialized(); }
            }

            public Monster(Monster source)
            {
                checked
                {
                    this.pos = source.pos != null ? new EGameFrame.Message.Vec3(source.pos) : null;
                    this.mana = source.mana;
                    this.hp = source.hp;
                    this.name = source.name;
                    this.friendly = source.friendly;
                    this.inventory = source.inventory?.ToList();
                    this.color = source.color;
                    this.weapons = source.weapons?.Select(x => x != null ? new EGameFrame.Message.Weapon(x) : null).ToList();
                    this.equipped = source.equipped?.Clone(x => x != null ? new EGameFrame.Message.Weapon(x) : null);
                    this.path = source.path?.Select(x => x != null ? new EGameFrame.Message.Vec3(x) : null).ToList();
                    this.OnInitialized();
                }
            }

            [FlatBufferItem(0)]
            public virtual global::EGameFrame.Message.Vec3 pos { get; set; }
            [FlatBufferItem(1, DefaultValue = (short)(150))]
            public virtual System.Int16 mana { get; set; } = (short)(150);
            [FlatBufferItem(2, DefaultValue = (short)(100))]
            public virtual System.Int16 hp { get; set; } = (short)(100);
            [FlatBufferItem(3)]
            public virtual System.String name { get; set; }
            [FlatBufferItem(4, DefaultValue = (bool)(false), Deprecated = true)]
            public virtual System.Boolean friendly { get; set; } = (bool)(false);
            [FlatBufferItem(5)]
            public virtual IList<System.Byte> inventory { get; set; }
            [FlatBufferItem(6, DefaultValue = global::EGameFrame.Message.Color.Blue)]
            public virtual global::EGameFrame.Message.Color color { get; set; } = global::EGameFrame.Message.Color.Blue;
            [FlatBufferItem(7)]
            public virtual IList<global::EGameFrame.Message.Weapon> weapons { get; set; }
            [FlatBufferItem(8)]
            public virtual global::EGameFrame.Message.Equipment equipped { get; set; }
            [FlatBufferItem(10)]
            public virtual IList<global::EGameFrame.Message.Vec3> path { get; set; }
            public static ISerializer<EGameFrame.Message.Monster> Serializer { get; } = new GeneratedSerializer().AsISerializer();

            #region Serializer for EGameFrame.Message.Monster

            [FlatSharpGeneratedSerializerAttribute(FlatBufferDeserializationOption.GreedyMutable)]
            private sealed class GeneratedSerializer : IGeneratedSerializer<EGameFrame.Message.Monster>
            {

                public void Write<TSpanWriter>(TSpanWriter writer, Span<byte> target, EGameFrame.Message.Monster root, int offset, SerializationContext context)
                    where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        WriteInlineValueOf_90d126455e0142959c3c185c29727317(writer, target, root, offset, context);
                    }
                }

                public int GetMaxSize(EGameFrame.Message.Monster root)
                {
                    checked
                    {
                        return GetMaxSizeOf_90d126455e0142959c3c185c29727317(root);
                    }
                }

                public EGameFrame.Message.Monster Parse<TInputBuffer>(TInputBuffer buffer, int offset)
                    where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return Read_90d126455e0142959c3c185c29727317(buffer, offset);
                    }
                }

                private static int GetMaxSizeOf_90d126455e0142959c3c185c29727317(EGameFrame.Message.Monster value)
                {
                    checked
                    {

                        int runningSum = 65 + 27;
                        var index3Value = value.name;

                        if (!object.ReferenceEquals(index3Value, null))
                        {
                            runningSum += GetMaxSizeOf_c991e3019b334ca09efff0b8f6aec64e(index3Value);
                        }
                        var index5Value = value.inventory;

                        if (!object.ReferenceEquals(index5Value, null))
                        {
                            runningSum += GetMaxSizeOf_14f1faa195ad47ee9a0c3d638a4ff4a6(index5Value);
                        }
                        var index7Value = value.weapons;

                        if (!object.ReferenceEquals(index7Value, null))
                        {
                            runningSum += GetMaxSizeOf_b58f8219a8ef4787bd3998f82fdf9dea(index7Value);
                        }
                        var index8Value = value.equipped;

                        if (!object.ReferenceEquals(index8Value, null))
                        {
                            runningSum += GetMaxSizeOf_b4809a3400674fdd8478fb300bd9e179(index8Value);
                        }
                        var index10Value = value.path;

                        if (!object.ReferenceEquals(index10Value, null))
                        {
                            runningSum += GetMaxSizeOf_d698372eaee6498a921018f09e8c4cde(index10Value);
                        };
                        return runningSum;

                    }
                }

                private static EGameFrame.Message.Monster Read_90d126455e0142959c3c185c29727317<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return new tableReader_6b845e7d8a1946c196c3bc3d9365834f<TInputBuffer>(buffer, offset + buffer.ReadUOffset(offset));
                    }
                }

                private sealed class tableReader_6b845e7d8a1946c196c3bc3d9365834f<TInputBuffer> : EGameFrame.Message.Monster where TInputBuffer : IInputBuffer
                {



                    public tableReader_6b845e7d8a1946c196c3bc3d9365834f(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            this.__index0 = __ReadIndex0Value(buffer, offset);
                            this.__index1 = __ReadIndex1Value(buffer, offset);
                            this.__index2 = __ReadIndex2Value(buffer, offset);
                            this.__index3 = __ReadIndex3Value(buffer, offset);
                            this.__index5 = __ReadIndex5Value(buffer, offset);
                            this.__index6 = __ReadIndex6Value(buffer, offset);
                            this.__index7 = __ReadIndex7Value(buffer, offset);
                            this.__index8 = __ReadIndex8Value(buffer, offset);
                            this.__index10 = __ReadIndex10Value(buffer, offset);
                        }
                    }

                    private EGameFrame.Message.Vec3 __index0;
                    public override EGameFrame.Message.Vec3 pos
                    {
                        get
                        {
                            checked
                            { return this.__index0; }
                        }

                        set
                        {
                            checked
                            { this.__index0 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static EGameFrame.Message.Vec3 __ReadIndex0Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 0);
                            if (absoluteLocation == 0)
                            {
                                return default(EGameFrame.Message.Vec3);
                            }
                            else
                            {
                                return Read_38da5b677fee4c37aa0e1e7a991e76bd(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.Int16 __index1;
                    public override System.Int16 mana
                    {
                        get
                        {
                            checked
                            { return this.__index1; }
                        }

                        set
                        {
                            checked
                            { this.__index1 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Int16 __ReadIndex1Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 1);
                            if (absoluteLocation == 0)
                            {
                                return (System.Int16)(150);
                            }
                            else
                            {
                                return Read_1d0517fa89b04e1890f20d238e0bd2fd(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.Int16 __index2;
                    public override System.Int16 hp
                    {
                        get
                        {
                            checked
                            { return this.__index2; }
                        }

                        set
                        {
                            checked
                            { this.__index2 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Int16 __ReadIndex2Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 2);
                            if (absoluteLocation == 0)
                            {
                                return (System.Int16)(100);
                            }
                            else
                            {
                                return Read_1d0517fa89b04e1890f20d238e0bd2fd(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.String __index3;
                    public override System.String name
                    {
                        get
                        {
                            checked
                            { return this.__index3; }
                        }

                        set
                        {
                            checked
                            { this.__index3 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.String __ReadIndex3Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 3);
                            if (absoluteLocation == 0)
                            {
                                return default(System.String);
                            }
                            else
                            {
                                return Read_c991e3019b334ca09efff0b8f6aec64e(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.Collections.Generic.IList<System.Byte> __index5;
                    public override System.Collections.Generic.IList<System.Byte> inventory
                    {
                        get
                        {
                            checked
                            { return this.__index5; }
                        }

                        set
                        {
                            checked
                            { this.__index5 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Collections.Generic.IList<System.Byte> __ReadIndex5Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 5);
                            if (absoluteLocation == 0)
                            {
                                return default(System.Collections.Generic.IList<System.Byte>);
                            }
                            else
                            {
                                return Read_14f1faa195ad47ee9a0c3d638a4ff4a6(buffer, absoluteLocation);
                            }
                        }
                    }

                    private EGameFrame.Message.Color __index6;
                    public override EGameFrame.Message.Color color
                    {
                        get
                        {
                            checked
                            { return this.__index6; }
                        }

                        set
                        {
                            checked
                            { this.__index6 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static EGameFrame.Message.Color __ReadIndex6Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 6);
                            if (absoluteLocation == 0)
                            {
                                return (EGameFrame.Message.Color)(System.SByte)(2);
                            }
                            else
                            {
                                return Read_65ad10fe25614095aec1cb8be733a6ac(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.Collections.Generic.IList<EGameFrame.Message.Weapon> __index7;
                    public override System.Collections.Generic.IList<EGameFrame.Message.Weapon> weapons
                    {
                        get
                        {
                            checked
                            { return this.__index7; }
                        }

                        set
                        {
                            checked
                            { this.__index7 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Collections.Generic.IList<EGameFrame.Message.Weapon> __ReadIndex7Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 7);
                            if (absoluteLocation == 0)
                            {
                                return default(System.Collections.Generic.IList<EGameFrame.Message.Weapon>);
                            }
                            else
                            {
                                return Read_b58f8219a8ef4787bd3998f82fdf9dea(buffer, absoluteLocation);
                            }
                        }
                    }

                    private EGameFrame.Message.Equipment __index8;
                    public override EGameFrame.Message.Equipment equipped
                    {
                        get
                        {
                            checked
                            { return this.__index8; }
                        }

                        set
                        {
                            checked
                            { this.__index8 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static EGameFrame.Message.Equipment __ReadIndex8Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int firstLocation = buffer.GetAbsoluteTableFieldLocation(offset, 8);
                            if (firstLocation == 0)
                            {
                                return default(EGameFrame.Message.Equipment);
                            }

                            var absoluteLocations = (firstLocation, buffer.GetAbsoluteTableFieldLocation(offset, 9));
                            return Read_b4809a3400674fdd8478fb300bd9e179(buffer, ref absoluteLocations);
                        }
                    }

                    private System.Collections.Generic.IList<EGameFrame.Message.Vec3> __index10;
                    public override System.Collections.Generic.IList<EGameFrame.Message.Vec3> path
                    {
                        get
                        {
                            checked
                            { return this.__index10; }
                        }

                        set
                        {
                            checked
                            { this.__index10 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Collections.Generic.IList<EGameFrame.Message.Vec3> __ReadIndex10Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 10);
                            if (absoluteLocation == 0)
                            {
                                return default(System.Collections.Generic.IList<EGameFrame.Message.Vec3>);
                            }
                            else
                            {
                                return Read_d698372eaee6498a921018f09e8c4cde(buffer, absoluteLocation);
                            }
                        }
                    }
                }



                private static void WriteInlineValueOf_90d126455e0142959c3c185c29727317<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    EGameFrame.Message.Monster value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        int tableStart = context.AllocateSpace(62, sizeof(int));
                        spanWriter.WriteUOffset(span, offset, tableStart, context);
                        int currentOffset = tableStart + sizeof(int); // skip past vtable soffset_t.

                        Span<byte> vtable = stackalloc byte[26];
                        int maxVtableIndex = -1;
                        vtable.Clear(); // reset to 0. Random memory from the stack isn't trustworthy.


                        var index0Value = value.pos;
                        var index0Offset = 0;
                        if (index0Value != default(EGameFrame.Message.Vec3))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index0Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 4, context);
                            maxVtableIndex = 0;
                            currentOffset += 12;

                        }

                        var index1Value = value.mana;
                        var index1Offset = 0;
                        if (index1Value != (System.Int16)(150))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 2);
                            index1Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 6, context);
                            maxVtableIndex = 1;
                            currentOffset += 2;

                        }

                        var index2Value = value.hp;
                        var index2Offset = 0;
                        if (index2Value != (System.Int16)(100))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 2);
                            index2Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 8, context);
                            maxVtableIndex = 2;
                            currentOffset += 2;

                        }

                        var index3Value = value.name;
                        var index3Offset = 0;
                        if (index3Value != default(System.String))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index3Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 10, context);
                            maxVtableIndex = 3;
                            currentOffset += 4;

                        }

                        var index5Value = value.inventory;
                        var index5Offset = 0;
                        if (index5Value != default(System.Collections.Generic.IList<System.Byte>))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index5Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 14, context);
                            maxVtableIndex = 5;
                            currentOffset += 4;

                        }

                        var index6Value = value.color;
                        var index6Offset = 0;
                        if (index6Value != (EGameFrame.Message.Color)(System.SByte)(2))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 1);
                            index6Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 16, context);
                            maxVtableIndex = 6;
                            currentOffset += 1;

                        }

                        var index7Value = value.weapons;
                        var index7Offset = 0;
                        if (index7Value != default(System.Collections.Generic.IList<EGameFrame.Message.Weapon>))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index7Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 18, context);
                            maxVtableIndex = 7;
                            currentOffset += 4;

                        }

                        var index8Value = value.equipped;
                        var index8Offset = 0;
                        var index9Offset = 0;
                        if (index8Value != default(EGameFrame.Message.Equipment))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 1);
                            index8Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 20, context);
                            maxVtableIndex = 8;
                            currentOffset += 1;


                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index9Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 22, context);
                            maxVtableIndex = 9;
                            currentOffset += 4;

                        }

                        var index10Value = value.path;
                        var index10Offset = 0;
                        if (index10Value != default(System.Collections.Generic.IList<EGameFrame.Message.Vec3>))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index10Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 24, context);
                            maxVtableIndex = 10;
                            currentOffset += 4;

                        }
                        int tableLength = currentOffset - tableStart;
                        context.Offset -= 62 - tableLength;
                        int vtableLength = 6 + (2 * maxVtableIndex);
                        spanWriter.WriteUShort(vtable, (ushort)vtableLength, 0, context);
                        spanWriter.WriteUShort(vtable, (ushort)tableLength, sizeof(ushort), context);
                        int vtablePosition = context.FinishVTable(span, vtable.Slice(0, vtableLength));
                        spanWriter.WriteInt(span, tableStart - vtablePosition, tableStart, context);

                        if (index0Offset != 0)
                        {
                            WriteInlineValueOf_38da5b677fee4c37aa0e1e7a991e76bd(
                                spanWriter,
                                span,
                                index0Value,
                                index0Offset,
                                context);

                        }

                        if (index1Offset != 0)
                        {
                            WriteInlineValueOf_1d0517fa89b04e1890f20d238e0bd2fd(
                                spanWriter,
                                span,
                                index1Value,
                                index1Offset,
                                context);

                        }

                        if (index2Offset != 0)
                        {
                            WriteInlineValueOf_1d0517fa89b04e1890f20d238e0bd2fd(
                                spanWriter,
                                span,
                                index2Value,
                                index2Offset,
                                context);

                        }

                        if (index3Offset != 0)
                        {
                            WriteInlineValueOf_c991e3019b334ca09efff0b8f6aec64e(
                                spanWriter,
                                span,
                                index3Value,
                                index3Offset,
                                context);

                        }

                        if (index5Offset != 0)
                        {
                            WriteInlineValueOf_14f1faa195ad47ee9a0c3d638a4ff4a6(
                                spanWriter,
                                span,
                                index5Value,
                                index5Offset,
                                context);

                        }

                        if (index6Offset != 0)
                        {
                            WriteInlineValueOf_65ad10fe25614095aec1cb8be733a6ac(
                                spanWriter,
                                span,
                                index6Value,
                                index6Offset,
                                context);

                        }

                        if (index7Offset != 0)
                        {
                            WriteInlineValueOf_b58f8219a8ef4787bd3998f82fdf9dea(
                                spanWriter,
                                span,
                                index7Value,
                                index7Offset,
                                context);

                        }

                        if (index8Offset != 0)
                        {
                            var offsetTuple = (index8Offset, index9Offset);
                            WriteInlineValueOf_b4809a3400674fdd8478fb300bd9e179(
                                spanWriter,
                                span,
                                index8Value,
                                ref offsetTuple,
                                context);

                        }

                        if (index10Offset != 0)
                        {
                            WriteInlineValueOf_d698372eaee6498a921018f09e8c4cde(
                                spanWriter,
                                span,
                                index10Value,
                                index10Offset,
                                context);

                        }
                    }
                }

                private static int GetMaxSizeOf_38da5b677fee4c37aa0e1e7a991e76bd(EGameFrame.Message.Vec3 value)
                {
                    checked
                    {
                        return 15;
                    }
                }

                private static EGameFrame.Message.Vec3 Read_38da5b677fee4c37aa0e1e7a991e76bd<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return new structReader_edda07ecd848444f8a222065f4dff046<TInputBuffer>(buffer, offset);
                    }
                }

                private sealed class structReader_edda07ecd848444f8a222065f4dff046<TInputBuffer> : EGameFrame.Message.Vec3 where TInputBuffer : IInputBuffer
                {



                    public structReader_edda07ecd848444f8a222065f4dff046(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            this.__index0 = __ReadIndex0Value(buffer, offset);
                            this.__index1 = __ReadIndex1Value(buffer, offset);
                            this.__index2 = __ReadIndex2Value(buffer, offset);
                        }
                    }

                    private System.Single __index0;
                    public override System.Single x
                    {
                        get
                        {
                            checked
                            { return this.__index0; }
                        }

                        set
                        {
                            checked
                            { this.__index0 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Single __ReadIndex0Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            return Read_e236e29c305c49148b7cfa64b0aa449c(buffer, (offset + 0));
                        }
                    }

                    private System.Single __index1;
                    public override System.Single y
                    {
                        get
                        {
                            checked
                            { return this.__index1; }
                        }

                        set
                        {
                            checked
                            { this.__index1 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Single __ReadIndex1Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            return Read_e236e29c305c49148b7cfa64b0aa449c(buffer, (offset + 4));
                        }
                    }

                    private System.Single __index2;
                    public override System.Single z
                    {
                        get
                        {
                            checked
                            { return this.__index2; }
                        }

                        set
                        {
                            checked
                            { this.__index2 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Single __ReadIndex2Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            return Read_e236e29c305c49148b7cfa64b0aa449c(buffer, (offset + 8));
                        }
                    }
                }



                private static void WriteInlineValueOf_38da5b677fee4c37aa0e1e7a991e76bd<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    EGameFrame.Message.Vec3 value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        WriteInlineValueOf_e236e29c305c49148b7cfa64b0aa449c(spanWriter, span, (value.x), (0 + offset), context);
                        WriteInlineValueOf_e236e29c305c49148b7cfa64b0aa449c(spanWriter, span, (value.y), (4 + offset), context);
                        WriteInlineValueOf_e236e29c305c49148b7cfa64b0aa449c(spanWriter, span, (value.z), (8 + offset), context);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static int GetMaxSizeOf_e236e29c305c49148b7cfa64b0aa449c(System.Single value)
                {
                    checked
                    {
                        return 7;
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static System.Single Read_e236e29c305c49148b7cfa64b0aa449c<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return buffer.ReadFloat(offset);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static void WriteInlineValueOf_e236e29c305c49148b7cfa64b0aa449c<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Single value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        spanWriter.WriteFloat(span, value, offset, context);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static int GetMaxSizeOf_1d0517fa89b04e1890f20d238e0bd2fd(System.Int16 value)
                {
                    checked
                    {
                        return 3;
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static System.Int16 Read_1d0517fa89b04e1890f20d238e0bd2fd<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return buffer.ReadShort(offset);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static void WriteInlineValueOf_1d0517fa89b04e1890f20d238e0bd2fd<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Int16 value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        spanWriter.WriteShort(span, value, offset, context);
                    }
                }

                private static int GetMaxSizeOf_c991e3019b334ca09efff0b8f6aec64e(System.String value)
                {
                    checked
                    {
                        return SerializationHelpers.GetMaxSize(value);
                    }
                }

                private static System.String Read_c991e3019b334ca09efff0b8f6aec64e<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return buffer.ReadString(offset);
                    }
                }

                private static void WriteInlineValueOf_c991e3019b334ca09efff0b8f6aec64e<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.String value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        spanWriter.WriteString(span, value, offset, context);
                    }
                }

                private static int GetMaxSizeOf_14f1faa195ad47ee9a0c3d638a4ff4a6(System.Collections.Generic.IList<System.Byte> value)
                {
                    checked
                    {
                        return 7 + 0 + (1 * value.Count);
                    }
                }

                private static System.Collections.Generic.IList<System.Byte> Read_14f1faa195ad47ee9a0c3d638a4ff4a6<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return (new FlatBufferVector_a8ba85b8a390432db572a1d3c1a76609<TInputBuffer>(
                            buffer,
                            offset + buffer.ReadUOffset(offset),
                            1)).FlatBufferVectorToList();
                    }
                }

                public sealed class FlatBufferVector_a8ba85b8a390432db572a1d3c1a76609<TInputBuffer> : FlatBufferVector<System.Byte, TInputBuffer>
                    where TInputBuffer : IInputBuffer
                {
                    public FlatBufferVector_a8ba85b8a390432db572a1d3c1a76609(
                        TInputBuffer memory,
                        int offset,
                        int itemSize) : base(memory, offset, itemSize)
                    {
                        checked
                        {
                        }
                    }

                    protected override System.Byte ParseItem(TInputBuffer memory, int offset)
                    {
                        checked
                        {
                            return Read_19ea0e07a6ef4974a7b2b31708d286bf(memory, offset);
                        }
                    }
                }



                private static void WriteInlineValueOf_14f1faa195ad47ee9a0c3d638a4ff4a6<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Collections.Generic.IList<System.Byte> value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        int count = value.Count;
                        int vectorOffset = context.AllocateVector(1, count, 1);
                        spanWriter.WriteUOffset(span, offset, vectorOffset, context);
                        spanWriter.WriteInt(span, count, vectorOffset, context);
                        vectorOffset += sizeof(int);
                        for (int i = 0; i < count; ++i)
                        {
                            var current = value[i];
                            ;
                            WriteInlineValueOf_19ea0e07a6ef4974a7b2b31708d286bf(spanWriter, span, current, vectorOffset, context);
                            vectorOffset += 1;
                        }
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static int GetMaxSizeOf_19ea0e07a6ef4974a7b2b31708d286bf(System.Byte value)
                {
                    checked
                    {
                        return 1;
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static System.Byte Read_19ea0e07a6ef4974a7b2b31708d286bf<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return buffer.ReadByte(offset);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static void WriteInlineValueOf_19ea0e07a6ef4974a7b2b31708d286bf<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Byte value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        spanWriter.WriteByte(span, value, offset, context);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static int GetMaxSizeOf_65ad10fe25614095aec1cb8be733a6ac(EGameFrame.Message.Color value)
                {
                    checked
                    {
                        return GetMaxSizeOf_4ebd177c98024d3a958300121149a329((System.SByte)value);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static EGameFrame.Message.Color Read_65ad10fe25614095aec1cb8be733a6ac<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return (EGameFrame.Message.Color)Read_4ebd177c98024d3a958300121149a329(buffer, offset);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static void WriteInlineValueOf_65ad10fe25614095aec1cb8be733a6ac<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    EGameFrame.Message.Color value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        WriteInlineValueOf_4ebd177c98024d3a958300121149a329(spanWriter, span, (System.SByte)value, offset, context);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static int GetMaxSizeOf_4ebd177c98024d3a958300121149a329(System.SByte value)
                {
                    checked
                    {
                        return 1;
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static System.SByte Read_4ebd177c98024d3a958300121149a329<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return buffer.ReadSByte(offset);
                    }
                }

                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                private static void WriteInlineValueOf_4ebd177c98024d3a958300121149a329<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.SByte value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {
                        spanWriter.WriteSByte(span, value, offset, context);
                    }
                }

                private static int GetMaxSizeOf_b58f8219a8ef4787bd3998f82fdf9dea(System.Collections.Generic.IList<EGameFrame.Message.Weapon> value)
                {
                    checked
                    {

                        int length = value.Count;
                        int runningSum = 7 + 7;
                        for (int i = 0; i < length; ++i)
                        {
                            var itemTemp = value[i];
                            SerializationHelpers.EnsureNonNull(itemTemp);
                            runningSum += GetMaxSizeOf_7dca4df1a1b84cb8b7854b21665f3208(itemTemp);
                        }
                        return runningSum;
                    }
                }

                private static System.Collections.Generic.IList<EGameFrame.Message.Weapon> Read_b58f8219a8ef4787bd3998f82fdf9dea<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return (new FlatBufferVector_932e508653b54bc5b84b54119f4020dc<TInputBuffer>(
                            buffer,
                            offset + buffer.ReadUOffset(offset),
                            4)).FlatBufferVectorToList();
                    }
                }

                public sealed class FlatBufferVector_932e508653b54bc5b84b54119f4020dc<TInputBuffer> : FlatBufferVector<EGameFrame.Message.Weapon, TInputBuffer>
                    where TInputBuffer : IInputBuffer
                {
                    public FlatBufferVector_932e508653b54bc5b84b54119f4020dc(
                        TInputBuffer memory,
                        int offset,
                        int itemSize) : base(memory, offset, itemSize)
                    {
                        checked
                        {
                        }
                    }

                    protected override EGameFrame.Message.Weapon ParseItem(TInputBuffer memory, int offset)
                    {
                        checked
                        {
                            return Read_7dca4df1a1b84cb8b7854b21665f3208(memory, offset);
                        }
                    }
                }



                private static void WriteInlineValueOf_b58f8219a8ef4787bd3998f82fdf9dea<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Collections.Generic.IList<EGameFrame.Message.Weapon> value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        int count = value.Count;
                        int vectorOffset = context.AllocateVector(4, count, 4);
                        spanWriter.WriteUOffset(span, offset, vectorOffset, context);
                        spanWriter.WriteInt(span, count, vectorOffset, context);
                        vectorOffset += sizeof(int);
                        for (int i = 0; i < count; ++i)
                        {
                            var current = value[i];
                            SerializationHelpers.EnsureNonNull(current);
                            WriteInlineValueOf_7dca4df1a1b84cb8b7854b21665f3208(spanWriter, span, current, vectorOffset, context);
                            vectorOffset += 4;
                        }
                    }
                }

                private static int GetMaxSizeOf_7dca4df1a1b84cb8b7854b21665f3208(EGameFrame.Message.Weapon value)
                {
                    checked
                    {

                        int runningSum = 17 + 9;
                        var index0Value = value.name;

                        if (!object.ReferenceEquals(index0Value, null))
                        {
                            runningSum += GetMaxSizeOf_c991e3019b334ca09efff0b8f6aec64e(index0Value);
                        };
                        return runningSum;

                    }
                }

                private static EGameFrame.Message.Weapon Read_7dca4df1a1b84cb8b7854b21665f3208<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return new tableReader_08068db6892646beb02fe5a2c0bad277<TInputBuffer>(buffer, offset + buffer.ReadUOffset(offset));
                    }
                }

                private sealed class tableReader_08068db6892646beb02fe5a2c0bad277<TInputBuffer> : EGameFrame.Message.Weapon where TInputBuffer : IInputBuffer
                {



                    public tableReader_08068db6892646beb02fe5a2c0bad277(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            this.__index0 = __ReadIndex0Value(buffer, offset);
                            this.__index1 = __ReadIndex1Value(buffer, offset);
                        }
                    }

                    private System.String __index0;
                    public override System.String name
                    {
                        get
                        {
                            checked
                            { return this.__index0; }
                        }

                        set
                        {
                            checked
                            { this.__index0 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.String __ReadIndex0Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 0);
                            if (absoluteLocation == 0)
                            {
                                return default(System.String);
                            }
                            else
                            {
                                return Read_c991e3019b334ca09efff0b8f6aec64e(buffer, absoluteLocation);
                            }
                        }
                    }

                    private System.Int16 __index1;
                    public override System.Int16 damage
                    {
                        get
                        {
                            checked
                            { return this.__index1; }
                        }

                        set
                        {
                            checked
                            { this.__index1 = value; }
                        }
                    }

                    [MethodImpl(MethodImplOptions.AggressiveInlining)]
                    private static System.Int16 __ReadIndex1Value(TInputBuffer buffer, int offset)
                    {
                        checked
                        {
                            int absoluteLocation = buffer.GetAbsoluteTableFieldLocation(offset, 1);
                            if (absoluteLocation == 0)
                            {
                                return default(System.Int16);
                            }
                            else
                            {
                                return Read_1d0517fa89b04e1890f20d238e0bd2fd(buffer, absoluteLocation);
                            }
                        }
                    }
                }



                private static void WriteInlineValueOf_7dca4df1a1b84cb8b7854b21665f3208<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    EGameFrame.Message.Weapon value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        int tableStart = context.AllocateSpace(14, sizeof(int));
                        spanWriter.WriteUOffset(span, offset, tableStart, context);
                        int currentOffset = tableStart + sizeof(int); // skip past vtable soffset_t.

                        Span<byte> vtable = stackalloc byte[8];
                        int maxVtableIndex = -1;
                        vtable.Clear(); // reset to 0. Random memory from the stack isn't trustworthy.


                        var index0Value = value.name;
                        var index0Offset = 0;
                        if (index0Value != default(System.String))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 4);
                            index0Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 4, context);
                            maxVtableIndex = 0;
                            currentOffset += 4;

                        }

                        var index1Value = value.damage;
                        var index1Offset = 0;
                        if (index1Value != default(System.Int16))
                        {

                            currentOffset += SerializationHelpers.GetAlignmentError(currentOffset, 2);
                            index1Offset = currentOffset;
                            spanWriter.WriteUShort(vtable, (ushort)(currentOffset - tableStart), 6, context);
                            maxVtableIndex = 1;
                            currentOffset += 2;

                        }
                        int tableLength = currentOffset - tableStart;
                        context.Offset -= 14 - tableLength;
                        int vtableLength = 6 + (2 * maxVtableIndex);
                        spanWriter.WriteUShort(vtable, (ushort)vtableLength, 0, context);
                        spanWriter.WriteUShort(vtable, (ushort)tableLength, sizeof(ushort), context);
                        int vtablePosition = context.FinishVTable(span, vtable.Slice(0, vtableLength));
                        spanWriter.WriteInt(span, tableStart - vtablePosition, tableStart, context);

                        if (index0Offset != 0)
                        {
                            WriteInlineValueOf_c991e3019b334ca09efff0b8f6aec64e(
                                spanWriter,
                                span,
                                index0Value,
                                index0Offset,
                                context);

                        }

                        if (index1Offset != 0)
                        {
                            WriteInlineValueOf_1d0517fa89b04e1890f20d238e0bd2fd(
                                spanWriter,
                                span,
                                index1Value,
                                index1Offset,
                                context);

                        }
                    }
                }

                private static int GetMaxSizeOf_b4809a3400674fdd8478fb300bd9e179(EGameFrame.Message.Equipment value)
                {
                    checked
                    {

                        switch (value.Discriminator)
                        {

                            case 1:
                                return GetMaxSizeOf_7dca4df1a1b84cb8b7854b21665f3208(value.Item1);
                            default:
                                throw new System.InvalidOperationException("Exception determining type of union. Discriminator = " + value.Discriminator);
                        }

                    }
                }

                private static EGameFrame.Message.Equipment Read_b4809a3400674fdd8478fb300bd9e179<TInputBuffer>(
                    TInputBuffer buffer,
                    ref (int offset0, int offset1) offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {

                        byte discriminator = buffer.ReadByte(offset.offset0);
                        int offsetLocation = offset.offset1;
                        if (discriminator == 0 && offsetLocation != 0)
                            throw new System.IO.InvalidDataException("FlatBuffer union had discriminator set but no offset.");

                        switch (discriminator)
                        {

                            case 1:

                                return new EGameFrame.Message.Equipment(Read_7dca4df1a1b84cb8b7854b21665f3208(buffer, offsetLocation));

                            default:
                                return null;
                        }

                    }
                }

                private static void WriteInlineValueOf_b4809a3400674fdd8478fb300bd9e179<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    EGameFrame.Message.Equipment value,
                    ref (int offset0, int offset1) offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        byte discriminatorValue = value.Discriminator;
                        spanWriter.WriteByte(
                            span,
                            discriminatorValue,
                            offset.offset0,
                            context);

                        switch (discriminatorValue)
                        {

                            case 1:
                                {
                                    var writeOffset = offset.offset1;
                                    WriteInlineValueOf_7dca4df1a1b84cb8b7854b21665f3208(spanWriter, span, value.Item1, writeOffset, context);
                                }
                                break;
                            default: throw new InvalidOperationException("Unexpected");
                        }
                    }
                }

                private static int GetMaxSizeOf_d698372eaee6498a921018f09e8c4cde(System.Collections.Generic.IList<EGameFrame.Message.Vec3> value)
                {
                    checked
                    {
                        return 7 + 3 + (12 * value.Count);
                    }
                }

                private static System.Collections.Generic.IList<EGameFrame.Message.Vec3> Read_d698372eaee6498a921018f09e8c4cde<TInputBuffer>(
                    TInputBuffer buffer,
                    int offset) where TInputBuffer : IInputBuffer
                {
                    checked
                    {
                        return (new FlatBufferVector_2a1667b34b3c422db858a391020ab443<TInputBuffer>(
                            buffer,
                            offset + buffer.ReadUOffset(offset),
                            12)).FlatBufferVectorToList();
                    }
                }

                public sealed class FlatBufferVector_2a1667b34b3c422db858a391020ab443<TInputBuffer> : FlatBufferVector<EGameFrame.Message.Vec3, TInputBuffer>
                    where TInputBuffer : IInputBuffer
                {
                    public FlatBufferVector_2a1667b34b3c422db858a391020ab443(
                        TInputBuffer memory,
                        int offset,
                        int itemSize) : base(memory, offset, itemSize)
                    {
                        checked
                        {
                        }
                    }

                    protected override EGameFrame.Message.Vec3 ParseItem(TInputBuffer memory, int offset)
                    {
                        checked
                        {
                            return Read_38da5b677fee4c37aa0e1e7a991e76bd(memory, offset);
                        }
                    }
                }



                private static void WriteInlineValueOf_d698372eaee6498a921018f09e8c4cde<TSpanWriter>(
                    TSpanWriter spanWriter,
                    Span<byte> span,
                    System.Collections.Generic.IList<EGameFrame.Message.Vec3> value,
                    int offset,
                    SerializationContext context) where TSpanWriter : ISpanWriter
                {
                    checked
                    {

                        int count = value.Count;
                        int vectorOffset = context.AllocateVector(4, count, 12);
                        spanWriter.WriteUOffset(span, offset, vectorOffset, context);
                        spanWriter.WriteInt(span, count, vectorOffset, context);
                        vectorOffset += sizeof(int);
                        for (int i = 0; i < count; ++i)
                        {
                            var current = value[i];
                            SerializationHelpers.EnsureNonNull(current);
                            WriteInlineValueOf_38da5b677fee4c37aa0e1e7a991e76bd(spanWriter, span, current, vectorOffset, context);
                            vectorOffset += 12;
                        }
                    }
                }
            }

            #endregion
        }
        [FlatBufferTable]
        [System.Runtime.CompilerServices.CompilerGenerated]
        public partial class Weapon : object
        {
            partial void OnInitialized();
            public Weapon()
            {
                checked
                { this.OnInitialized(); }
            }

            public Weapon(Weapon source)
            {
                checked
                {
                    this.name = source.name;
                    this.damage = source.damage;
                    this.OnInitialized();
                }
            }

            [FlatBufferItem(0)]
            public virtual System.String name { get; set; }
            [FlatBufferItem(1)]
            public virtual System.Int16 damage { get; set; }
        }
    }
}
